version: '3.8'
services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    ports:
      - "4444:4444"

  tests:
    build: .
    depends_on:
      - selenium
    environment:
      - BASE_API_URL=
      - BASE_UI_URL=
      - API_KEY=
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
      - TEST_TYPE=UI
    volumes:
      - ./reports:/app/target
