# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./home-task

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      env:
        API_KEY: ${{ secrets.API_KEY }} 
    - name: Build with Maven
      run: mvn test -Dtest=pl.inpost.home.task.runners.ApiTestRunner -Dapi.key=${{ secrets.API_KEY }} --file pom.xml -ntp 
    - name: Set Up Docker Compose
      run: docker compose up --build --abort-on-container-exit 
      continue-on-error: true
    - name: List files in target/
      run: ls -R target/ || echo "❌ Target directory not found!"
    - name: List files in reports/
      run: ls -R reports/ || echo "❌ Target directory not found!"
    - name: Archive target
      if: always()  
      uses: actions/upload-artifact@v4
      with:
        name: target with only reports
        path: 
          target/reports/**
          reports/**
